#!/usr/bin/python

import sys
import re
import os.path as path
import os


# Checking info
# ----------------------------------------------------------------------
if len(sys.argv) != 2:
	print("Usage: accidentalidad_app [file]")
	sys.exit(1)
	
if (path.exists(sys.argv[1]) == False):
	print("Not valid input file")
	sys.exit(1)


# Functions
# ----------------------------------------------------------------------

def day():
	orden = "spark-submit dia.py " + sys.argv[1]
	os.system(orden)
	
def district():
	orden = "spark-submit distrito.py " + sys.argv[1]
	os.system(orden)

def profile():
	orden = "spark-submit perfil.py" + " " + sys.argv[1]
	os.system(orden)

def district_day():
	dia = raw_input("	Provide a day: ")
	if(check_day(dia) == True):
		orden = "spark-submit dia_distrito.py " + sys.argv[1] + " " + dia
		os.system(orden)
	else:
		print("	Not valid day")
	
def district_street():
	dis = raw_input("	Provide a district: ")
	orden = "spark-submit distrito_calle.py " + sys.argv[1] + " " + dis
	os.system(orden)

def vehicle():
	orden = "spark-submit vehiculo.py " + sys.argv[1]
	os.system(orden)

def met_conditions():
	orden = "spark-submit met_conditions.py " + sys.argv[1]
	os.system(orden)

def show_districts():
	orden = "spark-submit show_districts.py " + sys.argv[1]
	os.system(orden)

def choose_street():
	dis = raw_input("	Provide a district: ")
	dia = raw_input("	Provide a day: ")
	if(check_day(dia) == True):
		orden = "spark-submit chooseStreet.py " + sys.argv[1] + " " + dis + " " + dia
		os.system(orden)
	else:
		print("	Not valid day")

def met_conditions_district():
	dis = raw_input("	Provide a district: ")
	orden = "spark-submit met_conditions_by_district.py " + sys.argv[1] + " " + dis
	os.system(orden)

def hours_district():
	dis = raw_input("	Provide a district: ")
	dia = raw_input("	Provide a day: ")

	if(check_day(dia) == True):
		orden = "spark-submit horasDistrito.py " + sys.argv[1] + " " + dis + " " + dia
		os.system(orden)
	else:
		print("	Not valid day")

def hours_place():
	dis = raw_input("	Provide a district: ")
	dia = raw_input("	Provide a day: ")

	if(check_day(dia) == True):
		orden = "spark-submit horasLugares.py " + sys.argv[1] + " " + dis + " " + dia
		os.system(orden)
	else:
		print("	Not valid day")
	
def check_day(d):
	d = d.upper()
	if(d != "LUNES" and d != "MARTES" and d != "MIERCOLES" and d != "JUEVES" \
	and d != "VIERNES" and d != "SABADO" and d != "DOMINGO"):
		return False
	return True


# Init
# ----------------------------------------------------------------------

print("\n")
print("------------------------------------------------------------------------------")
print("+		    Welcome to the Accident Application	        	    +")
print("------------------------------------------------------------------------------")
print("\n")
print("	      __---~~~~--__                      __--~~~~---__	")
print("	    `\---~~~~~~~~\\                    //~~~~~~~~---/'  	")
print("	      \/~~~~~~~~~\||                  ||/~~~~~~~~~\/ 	")
print("        	          `\\                //'			")
print("        	            `\\            //'			")
print("        	              ||          ||      			")
print("	            ______--~~~~~~~~~~~~~~~~~~--______             ")
print("	       ___ // _-~                        ~-_ \\ ___  	")
print("	      `\__)\/~        CLOUD & BIGDATA       ~\/(__/'       ")
print("	       _--`-___                            ___-'--_        ")
print("	     /~     `\ ~~~~~~~~------------~~~~~~~~ /'     ~\      ")
print("	    /|        `\         ________         /'        |\     ")
print("	   | `\   ______`\_      \------/      _/'______   /' |    ")
print("	   |   `\_~-_____\ ~-________________-~ /_____-~_/'   |  	")
print("	   `.     ~-__________________________________-~     .'    ")
print("	    `.      [_______/------|~~|------\_______]      .'	")
print("	     `\--___((____)(________\/________)(____))___--/'      ")
print("	      |>>>>>>||                            ||<<<<<<|	")
print("\n")


# main bucle
while True:
	print("\n")
	print("	MENU")
	print("------------------------------------------------------------------------------")
	print("	1. Day with highest accident rate")
	print("	2. District with the highest accident rate")
	print("	3. Profile with higher accident rate")
	print("	4. Most rugged district for each day of the week")
	print("	5. Most rugged street in a district")
	print("	6. Most rugged vehicle type")
	print("	7. Meteorological conditions that cause more accidents")
	print("	8. Show districts")
	print("	9. Choose street less rugged from a district")
	print("	10. Meteorological conditions that cause more accidents by district")
	print("	11. Hour with more accident rate in a district")
	print("        12. Hour with more accident rate in all places of a district")
	print("\n")
	print("	0. Exit")
	print("------------------------------------------------------------------------------")
    
	option = raw_input("	Select an option: ")
    
	avaiable = { '1': day, '2': district, '3': profile, '4': district_day,\
	'5': district_street, '6': vehicle, '7': met_conditions, '8' : show_districts,\
	'9' : choose_street, '10' : met_conditions_district, '11' : hours_district, '12' : hours_place}
 	
 	if option == '0':
 		print("\n")
		print("Bye!")
		sys.exit(1)
 	
 	try:
		result = avaiable[option]()

	except:    
		print("Not valid option")



		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
